### ISSUE TITLE
Exception: openxr_runtime_debugger.pdb not loaded

### ISSUE THREAD

**Issue by Zaniyar** [mattycorbett/HoloLens2-Facial-Detection-and-Localization#1]
openxr_runtime_debugger.pdb contains the debug information required to find the source for the module openxr_runtime_debugger.dll

Unhandled exception at 0x00007FFDCA58A15C (openxr_runtime_debugger.dll) in Hololens2FacialDetection.exe: 0xC0000005: Access violation reading location 0x000000000124F804.

**Comment by Zaniyar** [comment]
cleanup and rebuilding solved the problem

**Comment by matthew-corbett** [comment]
Great!  Hope it helps. Throw me a star if you like it

**Comment by Zaniyar** [comment]
I gave you a star :) 
"but" the app is really slow on H2, is that normal? I was hoping it works just a bit more accurate - it's loosing quite often the face and the tracking ways beyond what we know from snapchat, insta, tiktok... 
how could I tweak it so its a bit faster?

**Comment by matthew-corbett** [comment]
The inference reduces frame rates, but it shouldnt be terrible. The face loss is a limitation of the FaceDetector API, something built into Microsoft's Face Analysis tools (see [here](https://learn.microsoft.com/en-us/uwp/api/windows.media.faceanalysis.facedetector?view=winrt-22621)). If you click on the "FaceDetector" GameObject and look at the inspector, you see a field called "Sampling Interval".  You can make this longer and make the facial detections last longer by increasing the TTL value for faces in BoundingBoxScript.cs online 12.
